### ISSUE TITLE
Morning session: peer-to-peer code reviews (10/03/2023)

### ISSUE THREAD

**Issue by fmanimashaun** [blueberry1312/leaderboard#4]
Kindly add your comments below:

**Comment by jlvFlores** [comment]
Your project looks great so far, here are some personal recommendations:
- Make sure to remove unused code on your following commits.
- on your Index.js file on line 63 could you explain to me why you added the setTimeout, from my understanding you don't need to add a timer inside an asynchronous function.

Suggestion
I don't think you need localstorage, you can call the information from the API when your page loads and call it again when the refresh button is pressed.

**Comment by johnie261** [comment]
Make sure to remove unused functions,  like the removePlayer() in line 12, player.js

**Comment by blueberry1312** [comment]
Issues fixed. Thanks
